'use client';

import { useEffect, useState } from 'react';
type Draft={angle?:string;hook:string;caption:string;cta:string;score:number};
type Product={name:string;price?:string;commission?:string;url:string;niche?:string;problem?:string;rating?:string};
type QueueItem={id:string;status:string;product:Product;productScore:number;drafts:Draft[]};

export default function AffiliateAgent(){
 const [product,setProduct]=useState<Product>({name:'',price:'',commission:'',url:'',niche:'barang viral',problem:'',rating:''});
 const [drafts,setDrafts]=useState<Draft[]>([]); const [busy,setBusy]=useState(false); const [status,setStatus]=useState('Ready'); const [tab,setTab]=useState<'generator'|'queue'>('generator'); const [queue,setQueue]=useState<QueueItem[]>([]);
 async function loadQueue(){try{const r=await fetch('/api/affiliate/queue',{cache:'no-store'});const d=await r.json();if(r.ok)setQueue(d.items||[]);}catch{}}
 useEffect(()=>{loadQueue()},[]);
 async function generate(){if(!product.name||!product.url)return setStatus('Isi nama produk dan link affiliate dulu.');setBusy(true);setStatus('Agent sedang bekerja…');try{const r=await fetch('/api/affiliate/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Gagal');setDrafts(d.drafts||[]);setStatus(`Selesai · ${d.drafts?.length||0} draft`);}catch(e){setStatus(e instanceof Error?e.message:'Gagal')}finally{setBusy(false)}}
 function copy(d:Draft){navigator.clipboard?.writeText(`${d.hook}\n\n${d.caption}\n\n${d.cta}`);setStatus('Konten disalin ✓')}
 async function addQueue(){if(!drafts.length)return;setBusy(true);try{const item={id:`manual-${Date.now()}`,status:'ready_for_review',product,drafts,productScore:Math.max(...drafts.map(x=>x.score))};const r=await fetch('/api/affiliate/queue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,status:item.status,create:item})});if(!r.ok){const d=await r.json();throw new Error(d.error||'Gagal menyimpan queue')}setQueue(q=>[item,...q]);setTab('queue');setStatus('Masuk approval queue ✓')}catch(e){setStatus(e instanceof Error?e.message:'Gagal')}finally{setBusy(false)}}
 async function setItemStatus(id:string,status:string){try{const r=await fetch('/api/affiliate/queue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});if(!r.ok){const d=await r.json();throw new Error(d.error||'Gagal update')}setQueue(q=>q.map(x=>x.id===id?{...x,status}:x));setStatus(`${status} ✓`)}catch(e){setStatus(e instanceof Error?e.message:'Gagal')}}
 return <main style={{maxWidth:1150,margin:'0 auto',padding:'32px 18px',fontFamily:'system-ui'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'center',flexWrap:'wrap'}}><div><small style={{letterSpacing:2,opacity:.55}}>FREE · AFFILIATE AGENT</small><h1 style={{margin:'4px 0'}}>Affiliate Operator</h1><p style={{opacity:.65}}>Product → Score → Content → Approval → Publish</p></div><a href="/" style={{opacity:.65}}>← B20</a></header>
  <nav style={{display:'flex',gap:8,margin:'22px 0'}}>{[['generator','🤖 Generator'],['queue','📋 Approval Queue']].map(([k,label])=><button key={k} onClick={()=>{setTab(k as any);if(k==='queue')loadQueue()}} style={{padding:'10px 14px',borderRadius:10,border:'1px solid #ddd',fontWeight:tab===k?'700':'400'}}>{label}</button>)}</nav>
  {tab==='generator'?<>
   <section style={{border:'1px solid #ddd',borderRadius:16,padding:20}}><h2>1. Product Intelligence</h2><div style={{display:'grid',gap:10,gridTemplateColumns:'2fr 1fr 1fr'}}><input placeholder="Nama produk" value={product.name} onChange={e=>setProduct({...product,name:e.target.value})}/><input placeholder="Harga" value={product.price} onChange={e=>setProduct({...product,price:e.target.value})}/><input placeholder="Komisi / %" value={product.commission} onChange={e=>setProduct({...product,commission:e.target.value})}/></div><input style={{width:'100%',marginTop:10}} placeholder="Link affiliate" value={product.url} onChange={e=>setProduct({...product,url:e.target.value})}/><div style={{display:'grid',gap:10,gridTemplateColumns:'1fr 1fr',marginTop:10}}><input placeholder="Niche" value={product.niche} onChange={e=>setProduct({...product,niche:e.target.value})}/><input placeholder="Masalah yang diselesaikan" value={product.problem} onChange={e=>setProduct({...product,problem:e.target.value})}/></div><input style={{width:'100%',marginTop:10}} placeholder="Rating (opsional)" value={product.rating} onChange={e=>setProduct({...product,rating:e.target.value})}/><button onClick={generate} disabled={busy} style={{marginTop:14,padding:'12px 18px',borderRadius:10,border:0,cursor:'pointer'}}>{busy?'⚙️ Agent bekerja…':'✨ Generate 5 Konten'}</button><span style={{marginLeft:12,opacity:.6}}>{status}</span></section>
   {drafts.length>0&&<section style={{marginTop:20}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><h2>2. Content Studio</h2><button onClick={addQueue} disabled={busy} style={{padding:'10px 14px',borderRadius:10}}>✓ Save to Approval Queue</button></div><div style={{display:'grid',gap:12}}>{drafts.map((d,i)=><article key={i} style={{border:'1px solid #ddd',borderRadius:14,padding:16}}><div style={{display:'flex',justifyContent:'space-between'}}><b>#{i+1} · {d.angle||'AI angle'} · {d.score}/100</b><button onClick={()=>copy(d)}>Copy</button></div><h3>{d.hook}</h3><p style={{whiteSpace:'pre-wrap'}}>{d.caption}</p><p><b>{d.cta}</b></p></article>)}</div></section>}
  </>:<section><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:10,marginBottom:18}}>{[['Ready',queue.filter(x=>x.status==='ready_for_review').length],['Approved',queue.filter(x=>x.status==='approved').length],['Published',queue.filter(x=>x.status==='published').length],['Rejected',queue.filter(x=>x.status==='rejected').length]].map(x=><div key={String(x[0])} style={{border:'1px solid #ddd',borderRadius:14,padding:16}}><small>{x[0]}</small><h2 style={{margin:'5px 0'}}>{x[1]}</h2></div>)}</div><button onClick={loadQueue} style={{marginBottom:12}}>↻ Refresh</button>{queue.length===0?<div style={{padding:30,border:'1px dashed #bbb',borderRadius:14}}>Queue kosong.</div>:queue.map(item=><article key={item.id} style={{border:'1px solid #ddd',borderRadius:14,padding:18,marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',flexWrap:'wrap',gap:10}}><div><b>{item.product.name}</b><div style={{opacity:.65}}>Product score {item.productScore}/100 · {item.status}</div></div><div><button onClick={()=>setItemStatus(item.id,'approved')} style={{marginRight:8}}>✓ Approve</button><button onClick={()=>setItemStatus(item.id,'rejected')} style={{marginRight:8}}>✕ Reject</button>{item.status==='approved'&&<button onClick={()=>setItemStatus(item.id,'published')}>🚀 Published</button>}</div></div><div style={{display:'grid',gap:8,marginTop:12}}>{item.drafts.map((d,i)=><div key={i} style={{padding:12,border:'1px solid #eee',borderRadius:10}}><b>{d.angle||`Draft ${i+1}`}</b><p>{d.hook}</p><button onClick={()=>copy(d)}>Copy</button></div>)}</div></article>)}</section>}
  <footer style={{marginTop:30,fontSize:13,opacity:.55}}>Queue disimpan di GitHub. Publishing nyata hanya melalui API resmi platform.</footer>
 </main>
}
