'use client';

import { useState } from 'react';
import { useAccount, useConnect, useDisconnect, useWalletClient } from 'wagmi';
import { base } from 'viem/chains';
import { randomSalt } from '@/lib/b20';

type Token={name:string;symbol:string;about:string;image:string;salt:`0x${string}`;tokenAddress?:string;txHash?:string};
type Inspiration={name:string;symbol:string;network:string;volume24h:number;ageHours:number};
const STOP=new Set(['the','token','coin','finance','official','exchange','wrapped','weth','usdc','usdt','sol','eth','base','network','protocol','bot']);
const SUFFIX=['Club','Gang','Core','Maxx','IRL','Wave','Mode','World','Era','House'];
function parseCount(p:string){const m=p.match(/(\d{1,3})\s*(?:token|tokens)/i);return Math.min(Math.max(Number(m?.[1]||3),1),3)}
function words(n:string){return n.replace(/[^a-zA-Z0-9 ]/g,' ').split(/\s+/).filter(Boolean).filter(x=>x.length>=3&&!STOP.has(x.toLowerCase())).slice(0,3)}
function cap(s:string){return s.charAt(0).toUpperCase()+s.slice(1).toLowerCase()}
function fresh(s:Inspiration,i:number,pool:Inspiration[]){const a=cap(words(s.name)[0]||s.symbol||'Meme'),b=cap(words(pool[(i+1)%pool.length]?.name||'Base')[0]||'Base');return [`${a}${b}`,`${a} ${SUFFIX[i%SUFFIX.length]}`,`${a}${['y','o','ie','x','z'][i%5]}`][i%3]}
function ticker(n:string){const p=n.replace(/[^a-zA-Z0-9 ]/g,' ').split(/\s+/).filter(Boolean);return p.length>1?p.map(x=>x[0]).join('').toUpperCase().slice(0,5):(p[0]||'MEME').toUpperCase().slice(0,5)}
function imageFor(s:string){return `/api/token-image?q=${encodeURIComponent(s)}`}
function makeTokens(prompt:string,pool:Inspiration[]):Token[]{const src=pool.length?pool:[];const used=new Set<string>();return Array.from({length:parseCount(prompt)},(_,i)=>{const s=src[i%src.length];let name=fresh(s,i,src);let k=0;while(used.has(name.toLowerCase())&&k++<8)name+=k;used.add(name.toLowerCase());const symbol=ticker(name);return{name,symbol,about:`Inspired by ${s.name} — ${s.ageHours.toFixed(1)}h old, $${Math.round(s.volume24h).toLocaleString()} 24h volume.`,image:imageFor(s.name),salt:randomSalt(`${name}-${symbol}-${i}`)}})}

export default function Home(){
 const [prompt,setPrompt]=useState('Buatkan 3 token di Base, ambil inspirasi dari token trending yang baru dibuat sekitar 3 hari terakhir, volume minimal $1,000');
 const [tokens,setTokens]=useState<Token[]>([]),[status,setStatus]=useState('Ready'),[deployed,setDeployed]=useState(0);
 const {address,isConnected}=useAccount();const {connect,connectors,isPending}=useConnect();const {disconnect}=useDisconnect();const {data:walletClient}=useWalletClient();
 async function connectWallet(){const c=connectors.find(x=>x.ready!==false);if(!c){setStatus('Wallet connector unavailable.');return}try{setStatus('Opening wallet…');await connect({connector:c})}catch(e){setStatus(`Wallet connection failed: ${e instanceof Error?e.message:'Try again'}`)}}
 async function generate(){setStatus('Finding fresh Base trends…');try{const r=await fetch('/api/inspiration',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d?.error||'Trend feed unavailable');const p=Array.isArray(d?.inspirations)?d.inspirations as Inspiration[]:[];if(!p.length)throw new Error('No qualifying trends found.');setTokens(makeTokens(prompt,p));setDeployed(0);setStatus(`Generated ${Math.min(parseCount(prompt),3)} tokens from live trends.`)}catch(e){setStatus(`Generate failed: ${e instanceof Error?e.message:'Try again'}`)}}
 async function launch(){if(!address||!walletClient||!tokens.length)return;const t=tokens[deployed%tokens.length];try{setStatus(`Preparing low-gas B20 ${t.name}…`);const r=await fetch('/api/launch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:t.name,symbol:t.symbol,about:t.about,salt:t.salt,rewardRecipient:address})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Launch preparation failed');if(typeof walletClient.sendTransaction!=='function')throw new Error('Connected wallet cannot send a transaction.');setStatus(`Confirm Base Mainnet transaction for ${t.name}…`);const hash=await walletClient.sendTransaction({account:address,to:d.to,data:d.data as `0x${string}`,chain:base});setTokens(v=>v.map((x,i)=>i===deployed%tokens.length?{...x,tokenAddress:d.tokenAddress,txHash:hash}:x));setDeployed(v=>v+1);setStatus(`SUBMITTED — ${t.name} on Base Mainnet. Tx: ${hash.slice(0,12)}…`)}catch(e){setStatus(`Launch stopped: ${e instanceof Error?e.message:'Transaction rejected'}`)}}
 return <main className="wrap"><header><div><div className="eyebrow">BASE · B20 · LOW GAS</div><h1>AI Token Launcher</h1><p>Native B20 creation on Base Mainnet. No Paymaster.</p></div><div className="actions">{isConnected?<button className="ghost" onClick={()=>disconnect()}>{address?.slice(0,6)}…{address?.slice(-4)}</button>:<button disabled={isPending} onClick={connectWallet}>{isPending?'Opening…':'🟦 Connect Smart Wallet'}</button>}</div></header><section className="card hero"><label>Describe your launch</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={4}/><p className="pulseIntro">Gas mode: <b>direct Base transaction</b>. Paymaster removed. One B20 creation transaction per launch.</p><div className="actions"><button onClick={generate}>🔥 Generate From Live Trends</button>{isConnected&&tokens.length>0&&<button className="primary" onClick={launch}>🚀 Launch B20 — Low Gas</button>}</div><div className="status"><span className="dot"/>{status} · Base Mainnet</div></section>{tokens.length>0&&<section className="card"><div className="sectionHead"><h2>Generated Tokens</h2><span>{deployed}/{tokens.length} submitted</span></div><div className="grid">{tokens.map((t,i)=><article className="token" key={t.salt}><img src={t.image} alt={`${t.name} ${t.symbol}`} loading="lazy"/><div><strong>{t.name}</strong><b>${t.symbol}</b><p>{t.about}</p><small>🌐 Real web artwork · Native B20 Asset</small>{t.tokenAddress&&<small className="address">{t.tokenAddress}</small>}</div><small>#{i+1}</small></article>)}</div></section>}<section className="note"><strong>Flow:</strong> live trends → AI name/ticker → artwork → native B20 Asset → direct Base Mainnet transaction. <b>No Paymaster.</b></section></main>;
}
