'use client';

import { useEffect, useMemo, useState } from 'react';
import { useAccount, useCapabilities, useConnect, useDisconnect, useSendCalls } from 'wagmi';
import { base } from 'viem/chains';
import { randomSalt } from '@/lib/b20';

type Token={name:string;symbol:string;about:string;image:string;salt:`0x${string}`;tokenAddress?:string;txHash?:string;error?:string};
type BatchTx={to:`0x${string}`;data:`0x${string}`;value:string;count:number;start:number;end:number};
type Inspiration={name:string;symbol:string;network:string;volume24h:number;ageHours:number};
type News={title:string;source:string};
const STOP=new Set(['the','token','coin','finance','official','exchange','wrapped','weth','usdc','usdt','sol','eth','base','network','protocol','bot','crypto','cryptocurrency','meme','memecoin','memecoins']);
const MEME_WORDS=['Moon','Pump','Degen','Wagmi','Bonk','Rug','Bull','Bear','Chad','Pepe','Dog','Cat','Frog','Alpha','Viral','Hype','Send','Turbo','Brainrot','Rocket','Pudgy','Clown','Ape','Bark','Zoom'];
const BATCH_SIZE=100;
function parseCount(p:string){const m=p.match(/(\d{1,4})\s*(?:token|tokens)/i);return Math.min(Math.max(Number(m?.[1]||3),1),1000)}
function words(n:string){return n.replace(/[^a-zA-Z0-9 ]/g,' ').split(/\s+/).filter(Boolean).filter(x=>x.length>=3&&!STOP.has(x.toLowerCase())).slice(0,4)}
function cap(s:string){return s.charAt(0).toUpperCase()+s.slice(1).toLowerCase()}
function hashSeed(s:string){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0}
function randomFour(seed:string,i:number){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ';let n=hashSeed(`${seed}-${i}`),out='';for(let j=0;j<4;j++){n=(Math.imul(n,1664525)+1013904223)>>>0;out+=alphabet[n%26]}return out}
function newsWord(news:News[],i:number){const source=news.length?news[i%news.length]?.title||'':'';const w=words(source);return cap(w[i%Math.max(w.length,1)]||MEME_WORDS[i%MEME_WORDS.length])}
function fresh(s:Inspiration,i:number,pool:Inspiration[],news:News[]){const base=cap(words(s.name)[0]||s.symbol||'Meme');const nw=newsWord(news,i);const mw=MEME_WORDS[(hashSeed(`${s.symbol}-${i}`))%MEME_WORDS.length];const patterns=[`${nw}${mw}`,`${base}${nw}`,`${mw}${base}`,`${nw}${base}`,`${base}${mw}`];return patterns[i%patterns.length].slice(0,28)}
function imageFor(s:string){return `/api/token-image?q=${encodeURIComponent(s)}`}
function makeTokens(prompt:string,pool:Inspiration[],news:News[]):Token[]{const count=parseCount(prompt);const src=pool.length?pool:[{name:'Base',symbol:'BASE',network:'Base',volume24h:0,ageHours:0}];const used=new Set<string>();const usedSymbols=new Set<string>();return Array.from({length:count},(_,i)=>{const s=src[i%src.length];let name=fresh(s,i,src,news),k=0;while(used.has(name.toLowerCase())&&k++<1000)name=`${fresh(s,i+k,src,news)}${k}`;used.add(name.toLowerCase());let symbol=randomFour(`${name}-${news[i%Math.max(news.length,1)]?.title||'meme'}`,i),sk=0;while(usedSymbols.has(symbol)&&sk++<1000)symbol=randomFour(`${name}-${symbol}-${sk}`,i+sk);usedSymbols.add(symbol);return{name,symbol,about:`Meme-news inspired by ${s.name}${news.length?` · ${news[i%news.length].title} (${news[i%news.length].source})`:''} · ${s.ageHours.toFixed(1)}h old · $${Math.round(s.volume24h).toLocaleString()} 24h volume.`,image:imageFor(`${name} meme`),salt:randomSalt(`${name}-${symbol}-${i}-${Date.now()}`)}})}

export default function Home(){
 const [prompt,setPrompt]=useState('Buatkan 1000 token di Base, nama random berdasarkan meme news terbaru, ticker 4 huruf');
 const [tokens,setTokens]=useState<Token[]>([]),[status,setStatus]=useState('Ready'),[deployed,setDeployed]=useState(0),[running,setRunning]=useState(false),[batchTxs,setBatchTxs]=useState<BatchTx[]>([]),[batchIndex,setBatchIndex]=useState(0),[preparing,setPreparing]=useState(false),[submittedBatches,setSubmittedBatches]=useState(0);
 const {address,isConnected}=useAccount();const {connect,connectors,isPending}=useConnect();const {disconnect}=useDisconnect();
 const {data:walletCapabilities}=useCapabilities({account:address});
 const {sendCallsAsync,isPending:sendCallsPending,error:sendCallsError}=useSendCalls();
 const paymasterCapabilities=useMemo(()=>{const caps=address?walletCapabilities?.[base.id]:undefined;if(!caps?.paymasterService?.supported)return{};return{paymasterService:{url:'/api/paymaster'}} as const},[address,walletCapabilities]);
 const paymasterSupported=!!(address&&walletCapabilities?.[base.id]?.paymasterService?.supported);
 async function connectWallet(){const c=connectors.find(x=>x.ready!==false);if(!c){setStatus('Wallet connector unavailable.');return}try{setStatus('Opening wallet…');await connect({connector:c})}catch(e){setStatus(`Wallet connection failed: ${e instanceof Error?e.message:'Try again'}`)}}
 async function prepareBatches(list:Token[],wallet?:string){if(!list.length||!wallet){setBatchTxs([]);return}setPreparing(true);try{const chunks:Token[][]=[];for(let i=0;i<list.length;i+=BATCH_SIZE)chunks.push(list.slice(i,i+BATCH_SIZE));setStatus(`Preparing ${chunks.length} sponsored batches…`);const prepared=await Promise.all(chunks.map(async(chunk,index)=>{const r=await fetch('/api/launch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tokens:chunk.map(t=>({name:t.name,symbol:t.symbol,about:t.about,salt:t.salt,rewardRecipient:wallet}))})});const d=await r.json();if(!r.ok)throw new Error(d?.error||`Batch ${index+1} preparation failed`);return{to:d.to as `0x${string}`,data:d.data as `0x${string}`,value:String(d.value||'0x0'),count:chunk.length,start:index*BATCH_SIZE,end:index*BATCH_SIZE+chunk.length}}));setBatchTxs(prepared);setBatchIndex(0);setSubmittedBatches(0);setDeployed(0);setStatus(`${prepared.length} sponsored batches ready — ${list.length.toLocaleString()} launches total.`)}catch(e){setBatchTxs([]);setStatus(`Batch preparation failed: ${e instanceof Error?e.message:'Try again'}`)}finally{setPreparing(false)}}
 useEffect(()=>{if(address&&tokens.length)void prepareBatches(tokens,address);else{setBatchTxs([]);setBatchIndex(0)}},[address,tokens]);
 async function generate(){setStatus('Reading fresh meme trends + news…');setBatchTxs([]);try{const [r,n]=await Promise.all([fetch('/api/inspiration',{cache:'no-store'}),fetch('/api/news',{cache:'no-store'})]);const d=await r.json(),nd=await n.json();if(!r.ok)throw new Error(d?.error||'Trend feed unavailable');const p=Array.isArray(d?.inspirations)?d.inspirations as Inspiration[]:[];const news=Array.isArray(nd?.news)?nd.news as News[]:[];setTokens(makeTokens(prompt,p,news));setStatus(`Generated ${parseCount(prompt).toLocaleString()} random meme-news tokens with unique 4-letter tickers.`)}catch(e){setStatus(`Generate failed: ${e instanceof Error?e.message:'Try again'}`)}}
 async function launchNext(){if(!isConnected||!address||!batchTxs.length||running||batchIndex>=batchTxs.length)return;if(!paymasterSupported){setStatus('Gas sponsorship is not available for this connected wallet. Use a Smart Account/compatible Coinbase wallet.');return}setRunning(true);try{const b=batchTxs[batchIndex];setStatus(`Confirm sponsored batch ${batchIndex+1}/${batchTxs.length} — ${b.count} launches. You pay 0 ETH gas.`);const result=await sendCallsAsync({calls:[{to:b.to,data:b.data,value:BigInt(b.value)}],capabilities:paymasterCapabilities});setSubmittedBatches(v=>v+1);setDeployed(Math.min(tokens.length,b.end));setTokens(v=>v.map((x,i)=>i>=b.start&&i<b.end?{...x,txHash:result.id,error:undefined}:x));const next=batchIndex+1;setBatchIndex(next);if(next>=batchTxs.length)setStatus(`✅ ALL ${tokens.length.toLocaleString()} launches submitted with sponsored gas. User paid 0 ETH.`);else setStatus(`✅ Batch ${batchIndex+1}/${batchTxs.length} sponsored. Next: ${batchTxs[next].count} launches.`)}catch(e){const msg=e instanceof Error?e.message:(sendCallsError?.message||'Sponsored transaction rejected');setStatus(`Sponsored batch failed: ${msg}`);setTokens(v=>v.map(x=>({...x,error:msg})));}finally{setRunning(false)}}
 const totalBatches=batchTxs.length;const remaining=Math.max(totalBatches-submittedBatches,0);
 return <main className="wrap"><header><div><div className="eyebrow">BASE · OPENLAUNCH · CDP PAYMASTER</div><h1>AI Token Launcher</h1><p>Up to 1,000 tokens on Base Mainnet with sponsored gas.</p></div><div className="actions">{isConnected?<button className="ghost" onClick={()=>disconnect()}>{address?.slice(0,6)}…{address?.slice(-4)}</button>:<button disabled={isPending} onClick={connectWallet}>{isPending?'Opening…':'🟦 Connect Wallet'}</button>}</div></header><section className="card hero"><label>Describe your launch</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={4}/><p className="pulseIntro">Names come from fresh meme-token trends + recent meme/crypto headlines. Every ticker is <b>exactly 4 letters</b>. Gas is sponsored by the app through Coinbase CDP Paymaster, so the connected user does not need ETH for launch gas.</p><div className="actions"><button disabled={running||preparing} onClick={generate}>🔥 Generate Up To 1,000</button>{isConnected&&tokens.length>0&&<button className="primary" disabled={running||preparing||!batchTxs.length||batchIndex>=batchTxs.length||!paymasterSupported||sendCallsPending} onClick={launchNext}>{running||sendCallsPending?'🚀 Waiting for Wallet…':preparing?'⚙️ Preparing Sponsored Batches…':!paymasterSupported?'⚠️ Gas Sponsor Not Available':batchIndex>=batchTxs.length?`✅ ${tokens.length.toLocaleString()} Launched`: `🚀 Launch Batch ${batchIndex+1}/${batchTxs.length} — ${batchTxs[batchIndex]?.count||0} Tokens`}</button>}</div><div className="status"><span className="dot"/>{status} · Base Mainnet · {paymasterSupported?'💸 Gas Sponsored':'⚠️ Sponsor unavailable'}</div></section>{tokens.length>0&&<section className="card"><div className="sectionHead"><h2>Generated Tokens</h2><span>{deployed.toLocaleString()}/{tokens.length.toLocaleString()} submitted · {remaining} batches left</span></div><div className="grid">{tokens.slice(0,100).map((t,i)=><article className="token" key={t.salt}><img src={t.image} alt={`${t.name} ${t.symbol}`} loading="lazy"/><div><strong>{t.name}</strong><b>${t.symbol}</b><p>{t.about}</p><small>{t.txHash?`✅ sponsored ${t.txHash.slice(0,12)}…`:t.error?`❌ ${t.error}`:'⏳ queued'} · OpenLaunch Base</small></div><small>#{i+1}</small></article>)}</div>{tokens.length>100&&<p className="pulseIntro">Showing first 100 cards for performance. The full {tokens.length.toLocaleString()}-token queue is retained in memory.</p>}</section>}<section className="note"><strong>Flow:</strong> fresh meme/crypto news → randomized name → unique 4-letter ticker → OpenLaunch ERC-20 → Uniswap v4. <b>Gas sponsored by CDP Paymaster.</b> Because the previous 1,000-call payload exceeded Coinbase's 260 KB UserOperation limit, launches are automatically split into 100-token sponsored batches. You pay 0 ETH gas; the app/CDP account pays the sponsored gas subject to its Paymaster policy and credits.</section></main>;
}
